import { Inter,Poppins,Space_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });
const banglaFont=Space_Grotesk({subsets:["latin"],weight:"400",style:"normal"})

export const metadata = {
  title: "Mazaharul",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={banglaFont.className}>
        <div className="bg-gray-100 h-full px-4 py-2 md:grid md:grid-cols-4">
       <div className="md:col-span-1 ">
       <Sidebar/>
       </div>
        <div className="md:col-span-3">
        {children}
        </div>
      
        </div>
      </body>
    </html>
  );
}
